title: Luiz A. Astorga Arambula
author: (214) 607 5998
email: laa180001@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a motivated, proactive, and diligent student seeking experience in order to obtain a full-time job after college

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  LuizAstorga # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
